//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PreuvaWIndo.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsMCTuristicSoap", Namespace="http://tempuri.org/")]
    public partial class WsMCTuristic : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EliminarDireccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarDireccionOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarDireccionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsMCTuristic() {
            this.Url = global::PreuvaWIndo.Properties.Settings.Default.PreuvaWIndo_localhost_WsMCTuristic;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertarUsuarioCompletedEventHandler InsertarUsuarioCompleted;
        
        /// <remarks/>
        public event ModificarUsuarioCompletedEventHandler ModificarUsuarioCompleted;
        
        /// <remarks/>
        public event EliminarUsuarioCompletedEventHandler EliminarUsuarioCompleted;
        
        /// <remarks/>
        public event EliminarDireccionCompletedEventHandler EliminarDireccionCompleted;
        
        /// <remarks/>
        public event InsertarDireccionCompletedEventHandler InsertarDireccionCompleted;
        
        /// <remarks/>
        public event ModificarDireccionCompletedEventHandler ModificarDireccionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertarUsuario(UsuarioBO obj) {
            object[] results = this.Invoke("InsertarUsuario", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarUsuarioAsync(UsuarioBO obj) {
            this.InsertarUsuarioAsync(obj, null);
        }
        
        /// <remarks/>
        public void InsertarUsuarioAsync(UsuarioBO obj, object userState) {
            if ((this.InsertarUsuarioOperationCompleted == null)) {
                this.InsertarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarUsuarioOperationCompleted);
            }
            this.InvokeAsync("InsertarUsuario", new object[] {
                        obj}, this.InsertarUsuarioOperationCompleted, userState);
        }
        
        private void OnInsertarUsuarioOperationCompleted(object arg) {
            if ((this.InsertarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarUsuarioCompleted(this, new InsertarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ModificarUsuario(UsuarioBO obj) {
            object[] results = this.Invoke("ModificarUsuario", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(UsuarioBO obj) {
            this.ModificarUsuarioAsync(obj, null);
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(UsuarioBO obj, object userState) {
            if ((this.ModificarUsuarioOperationCompleted == null)) {
                this.ModificarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ModificarUsuario", new object[] {
                        obj}, this.ModificarUsuarioOperationCompleted, userState);
        }
        
        private void OnModificarUsuarioOperationCompleted(object arg) {
            if ((this.ModificarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarUsuarioCompleted(this, new ModificarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EliminarUsuario(UsuarioBO obj) {
            object[] results = this.Invoke("EliminarUsuario", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarUsuarioAsync(UsuarioBO obj) {
            this.EliminarUsuarioAsync(obj, null);
        }
        
        /// <remarks/>
        public void EliminarUsuarioAsync(UsuarioBO obj, object userState) {
            if ((this.EliminarUsuarioOperationCompleted == null)) {
                this.EliminarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarUsuarioOperationCompleted);
            }
            this.InvokeAsync("EliminarUsuario", new object[] {
                        obj}, this.EliminarUsuarioOperationCompleted, userState);
        }
        
        private void OnEliminarUsuarioOperationCompleted(object arg) {
            if ((this.EliminarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarUsuarioCompleted(this, new EliminarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EliminarDireccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EliminarDireccion(DireccionBO obj) {
            object[] results = this.Invoke("EliminarDireccion", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EliminarDireccionAsync(DireccionBO obj) {
            this.EliminarDireccionAsync(obj, null);
        }
        
        /// <remarks/>
        public void EliminarDireccionAsync(DireccionBO obj, object userState) {
            if ((this.EliminarDireccionOperationCompleted == null)) {
                this.EliminarDireccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEliminarDireccionOperationCompleted);
            }
            this.InvokeAsync("EliminarDireccion", new object[] {
                        obj}, this.EliminarDireccionOperationCompleted, userState);
        }
        
        private void OnEliminarDireccionOperationCompleted(object arg) {
            if ((this.EliminarDireccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EliminarDireccionCompleted(this, new EliminarDireccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarDireccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int InsertarDireccion(DireccionBO obj) {
            object[] results = this.Invoke("InsertarDireccion", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarDireccionAsync(DireccionBO obj) {
            this.InsertarDireccionAsync(obj, null);
        }
        
        /// <remarks/>
        public void InsertarDireccionAsync(DireccionBO obj, object userState) {
            if ((this.InsertarDireccionOperationCompleted == null)) {
                this.InsertarDireccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarDireccionOperationCompleted);
            }
            this.InvokeAsync("InsertarDireccion", new object[] {
                        obj}, this.InsertarDireccionOperationCompleted, userState);
        }
        
        private void OnInsertarDireccionOperationCompleted(object arg) {
            if ((this.InsertarDireccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarDireccionCompleted(this, new InsertarDireccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarDireccion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ModificarDireccion(DireccionBO obj) {
            object[] results = this.Invoke("ModificarDireccion", new object[] {
                        obj});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ModificarDireccionAsync(DireccionBO obj) {
            this.ModificarDireccionAsync(obj, null);
        }
        
        /// <remarks/>
        public void ModificarDireccionAsync(DireccionBO obj, object userState) {
            if ((this.ModificarDireccionOperationCompleted == null)) {
                this.ModificarDireccionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarDireccionOperationCompleted);
            }
            this.InvokeAsync("ModificarDireccion", new object[] {
                        obj}, this.ModificarDireccionOperationCompleted, userState);
        }
        
        private void OnModificarDireccionOperationCompleted(object arg) {
            if ((this.ModificarDireccionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarDireccionCompleted(this, new ModificarDireccionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UsuarioBO {
        
        private int idUsuarioField;
        
        private System.DateTime fecharNacUsuarioField;
        
        private string telefonoUsuarioField;
        
        private string contraseñaUsuarioField;
        
        private string emailUsuarioField;
        
        private string apellidosUsuarioField;
        
        private string nombreUsuarioField;
        
        /// <comentarios/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FecharNacUsuario {
            get {
                return this.fecharNacUsuarioField;
            }
            set {
                this.fecharNacUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string TelefonoUsuario {
            get {
                return this.telefonoUsuarioField;
            }
            set {
                this.telefonoUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string ContraseñaUsuario {
            get {
                return this.contraseñaUsuarioField;
            }
            set {
                this.contraseñaUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string EmailUsuario {
            get {
                return this.emailUsuarioField;
            }
            set {
                this.emailUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string ApellidosUsuario {
            get {
                return this.apellidosUsuarioField;
            }
            set {
                this.apellidosUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string NombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DireccionBO {
        
        private int idDireccionField;
        
        private int idAdministradorField;
        
        private int idUsuarioField;
        
        private string codPostalField;
        
        private string estadoField;
        
        private string coloniaField;
        
        private string descripcionDireccionField;
        
        private string numeroField;
        
        private string cruzamientoField;
        
        private string calleField;
        
        /// <comentarios/>
        public int IdDireccion {
            get {
                return this.idDireccionField;
            }
            set {
                this.idDireccionField = value;
            }
        }
        
        /// <comentarios/>
        public int IdAdministrador {
            get {
                return this.idAdministradorField;
            }
            set {
                this.idAdministradorField = value;
            }
        }
        
        /// <comentarios/>
        public int IdUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string CodPostal {
            get {
                return this.codPostalField;
            }
            set {
                this.codPostalField = value;
            }
        }
        
        /// <comentarios/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <comentarios/>
        public string Colonia {
            get {
                return this.coloniaField;
            }
            set {
                this.coloniaField = value;
            }
        }
        
        /// <comentarios/>
        public string DescripcionDireccion {
            get {
                return this.descripcionDireccionField;
            }
            set {
                this.descripcionDireccionField = value;
            }
        }
        
        /// <comentarios/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <comentarios/>
        public string Cruzamiento {
            get {
                return this.cruzamientoField;
            }
            set {
                this.cruzamientoField = value;
            }
        }
        
        /// <comentarios/>
        public string Calle {
            get {
                return this.calleField;
            }
            set {
                this.calleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertarUsuarioCompletedEventHandler(object sender, InsertarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ModificarUsuarioCompletedEventHandler(object sender, ModificarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void EliminarUsuarioCompletedEventHandler(object sender, EliminarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void EliminarDireccionCompletedEventHandler(object sender, EliminarDireccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EliminarDireccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EliminarDireccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void InsertarDireccionCompletedEventHandler(object sender, InsertarDireccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarDireccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarDireccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ModificarDireccionCompletedEventHandler(object sender, ModificarDireccionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ModificarDireccionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ModificarDireccionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591