//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace divisasWS.wbDivisa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.webserviceX.NET/", ConfigurationName="wbDivisa.CurrencyConvertorSoap")]
    public interface CurrencyConvertorSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ConversionRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        double ConversionRate(divisasWS.wbDivisa.Currency FromCurrency, divisasWS.wbDivisa.Currency ToCurrency);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.webserviceX.NET/ConversionRate", ReplyAction="*")]
        System.Threading.Tasks.Task<double> ConversionRateAsync(divisasWS.wbDivisa.Currency FromCurrency, divisasWS.wbDivisa.Currency ToCurrency);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.webserviceX.NET/")]
    public enum Currency {
        
        /// <comentarios/>
        AFA,
        
        /// <comentarios/>
        ALL,
        
        /// <comentarios/>
        DZD,
        
        /// <comentarios/>
        ARS,
        
        /// <comentarios/>
        AWG,
        
        /// <comentarios/>
        AUD,
        
        /// <comentarios/>
        BSD,
        
        /// <comentarios/>
        BHD,
        
        /// <comentarios/>
        BDT,
        
        /// <comentarios/>
        BBD,
        
        /// <comentarios/>
        BZD,
        
        /// <comentarios/>
        BMD,
        
        /// <comentarios/>
        BTN,
        
        /// <comentarios/>
        BOB,
        
        /// <comentarios/>
        BWP,
        
        /// <comentarios/>
        BRL,
        
        /// <comentarios/>
        GBP,
        
        /// <comentarios/>
        BND,
        
        /// <comentarios/>
        BIF,
        
        /// <comentarios/>
        XOF,
        
        /// <comentarios/>
        XAF,
        
        /// <comentarios/>
        KHR,
        
        /// <comentarios/>
        CAD,
        
        /// <comentarios/>
        CVE,
        
        /// <comentarios/>
        KYD,
        
        /// <comentarios/>
        CLP,
        
        /// <comentarios/>
        CNY,
        
        /// <comentarios/>
        COP,
        
        /// <comentarios/>
        KMF,
        
        /// <comentarios/>
        CRC,
        
        /// <comentarios/>
        HRK,
        
        /// <comentarios/>
        CUP,
        
        /// <comentarios/>
        CYP,
        
        /// <comentarios/>
        CZK,
        
        /// <comentarios/>
        DKK,
        
        /// <comentarios/>
        DJF,
        
        /// <comentarios/>
        DOP,
        
        /// <comentarios/>
        XCD,
        
        /// <comentarios/>
        EGP,
        
        /// <comentarios/>
        SVC,
        
        /// <comentarios/>
        EEK,
        
        /// <comentarios/>
        ETB,
        
        /// <comentarios/>
        EUR,
        
        /// <comentarios/>
        FKP,
        
        /// <comentarios/>
        GMD,
        
        /// <comentarios/>
        GHC,
        
        /// <comentarios/>
        GIP,
        
        /// <comentarios/>
        XAU,
        
        /// <comentarios/>
        GTQ,
        
        /// <comentarios/>
        GNF,
        
        /// <comentarios/>
        GYD,
        
        /// <comentarios/>
        HTG,
        
        /// <comentarios/>
        HNL,
        
        /// <comentarios/>
        HKD,
        
        /// <comentarios/>
        HUF,
        
        /// <comentarios/>
        ISK,
        
        /// <comentarios/>
        INR,
        
        /// <comentarios/>
        IDR,
        
        /// <comentarios/>
        IQD,
        
        /// <comentarios/>
        ILS,
        
        /// <comentarios/>
        JMD,
        
        /// <comentarios/>
        JPY,
        
        /// <comentarios/>
        JOD,
        
        /// <comentarios/>
        KZT,
        
        /// <comentarios/>
        KES,
        
        /// <comentarios/>
        KRW,
        
        /// <comentarios/>
        KWD,
        
        /// <comentarios/>
        LAK,
        
        /// <comentarios/>
        LVL,
        
        /// <comentarios/>
        LBP,
        
        /// <comentarios/>
        LSL,
        
        /// <comentarios/>
        LRD,
        
        /// <comentarios/>
        LYD,
        
        /// <comentarios/>
        LTL,
        
        /// <comentarios/>
        MOP,
        
        /// <comentarios/>
        MKD,
        
        /// <comentarios/>
        MGF,
        
        /// <comentarios/>
        MWK,
        
        /// <comentarios/>
        MYR,
        
        /// <comentarios/>
        MVR,
        
        /// <comentarios/>
        MTL,
        
        /// <comentarios/>
        MRO,
        
        /// <comentarios/>
        MUR,
        
        /// <comentarios/>
        MXN,
        
        /// <comentarios/>
        MDL,
        
        /// <comentarios/>
        MNT,
        
        /// <comentarios/>
        MAD,
        
        /// <comentarios/>
        MZM,
        
        /// <comentarios/>
        MMK,
        
        /// <comentarios/>
        NAD,
        
        /// <comentarios/>
        NPR,
        
        /// <comentarios/>
        ANG,
        
        /// <comentarios/>
        NZD,
        
        /// <comentarios/>
        NIO,
        
        /// <comentarios/>
        NGN,
        
        /// <comentarios/>
        KPW,
        
        /// <comentarios/>
        NOK,
        
        /// <comentarios/>
        OMR,
        
        /// <comentarios/>
        XPF,
        
        /// <comentarios/>
        PKR,
        
        /// <comentarios/>
        XPD,
        
        /// <comentarios/>
        PAB,
        
        /// <comentarios/>
        PGK,
        
        /// <comentarios/>
        PYG,
        
        /// <comentarios/>
        PEN,
        
        /// <comentarios/>
        PHP,
        
        /// <comentarios/>
        XPT,
        
        /// <comentarios/>
        PLN,
        
        /// <comentarios/>
        QAR,
        
        /// <comentarios/>
        ROL,
        
        /// <comentarios/>
        RUB,
        
        /// <comentarios/>
        WST,
        
        /// <comentarios/>
        STD,
        
        /// <comentarios/>
        SAR,
        
        /// <comentarios/>
        SCR,
        
        /// <comentarios/>
        SLL,
        
        /// <comentarios/>
        XAG,
        
        /// <comentarios/>
        SGD,
        
        /// <comentarios/>
        SKK,
        
        /// <comentarios/>
        SIT,
        
        /// <comentarios/>
        SBD,
        
        /// <comentarios/>
        SOS,
        
        /// <comentarios/>
        ZAR,
        
        /// <comentarios/>
        LKR,
        
        /// <comentarios/>
        SHP,
        
        /// <comentarios/>
        SDD,
        
        /// <comentarios/>
        SRG,
        
        /// <comentarios/>
        SZL,
        
        /// <comentarios/>
        SEK,
        
        /// <comentarios/>
        CHF,
        
        /// <comentarios/>
        SYP,
        
        /// <comentarios/>
        TWD,
        
        /// <comentarios/>
        TZS,
        
        /// <comentarios/>
        THB,
        
        /// <comentarios/>
        TOP,
        
        /// <comentarios/>
        TTD,
        
        /// <comentarios/>
        TND,
        
        /// <comentarios/>
        TRL,
        
        /// <comentarios/>
        USD,
        
        /// <comentarios/>
        AED,
        
        /// <comentarios/>
        UGX,
        
        /// <comentarios/>
        UAH,
        
        /// <comentarios/>
        UYU,
        
        /// <comentarios/>
        VUV,
        
        /// <comentarios/>
        VEB,
        
        /// <comentarios/>
        VND,
        
        /// <comentarios/>
        YER,
        
        /// <comentarios/>
        YUM,
        
        /// <comentarios/>
        ZMK,
        
        /// <comentarios/>
        ZWD,
        
        /// <comentarios/>
        TRY,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CurrencyConvertorSoapChannel : divisasWS.wbDivisa.CurrencyConvertorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyConvertorSoapClient : System.ServiceModel.ClientBase<divisasWS.wbDivisa.CurrencyConvertorSoap>, divisasWS.wbDivisa.CurrencyConvertorSoap {
        
        public CurrencyConvertorSoapClient() {
        }
        
        public CurrencyConvertorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyConvertorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConvertorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConvertorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double ConversionRate(divisasWS.wbDivisa.Currency FromCurrency, divisasWS.wbDivisa.Currency ToCurrency) {
            return base.Channel.ConversionRate(FromCurrency, ToCurrency);
        }
        
        public System.Threading.Tasks.Task<double> ConversionRateAsync(divisasWS.wbDivisa.Currency FromCurrency, divisasWS.wbDivisa.Currency ToCurrency) {
            return base.Channel.ConversionRateAsync(FromCurrency, ToCurrency);
        }
    }
}
